"""Initial schema from Phase 1-4

Revision ID: 67543c0e8517
Revises:
Create Date: 2025-10-31 09:27:59.672006

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '67543c0e8517'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
